name: train-my-model

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    container: 
      image: docker://davidgortega/cml:runner

    steps:
      - uses: actions/checkout@v2

      - name: deploy
        shell: bash
        env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=g3.4xlarge \
          --cloud-hdd-size 64 \
          --labels=cml-runner \
          --ssh-private=${{ secrets.SSH_PRIVATE }} \
          --idle-timeout=600 \
          --cloud-startup-script=c3VkbyBlY2hvICdoZWxsbyB3b3JsZCcgPj4gL3Vzci9oZWxsby50eHQ=

  run:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: 
      image: docker://davidgortega/cml:runner
      options: --gpus all

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: cml
      env:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        apt-get update -y
        apt install imagemagick -y
        pip install -r requirements.txt
        
        # DVC stuff
        git fetch --prune
        dvc repro
        
        echo "# Style transfer" >> report.md
        git show origin/master:final_owl.png > master_owl.png
        convert +append final_owl.png master_owl.png out.png
        convert out.png -resize 75%  out_shrink.png
        echo "### Workspace vs. Main" >> report.md
        cml-publish out_shrink.png --md --title 'compare' >> report.md
        
        echo "## Training metrics" >> report.md
        dvc params diff master --show-md >> report.md
        
        echo >> report.md
        echo "## GPU info" >> report.md
        cat gpu_info.txt >> report.md
        
        cml-send-comment report.md 
