name: CML Report
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy-runner:
    if: github.actor == 'iterative-studio[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci --fetch-depth 0
          cml comment create --pr --publish results/evaluate/report.md
