name: Act on artifact registrations and promotions
on:
  push:
    tags:
      - "*"

jobs:
  act:
    name: Figure out what was registered/promoted and act on it
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "GTO: figure out what was registered/promoted and show the Registry state"
      id: gto
      uses: iterative/gto-action@v1
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: "Publish (act on registering a new version)"
      if: steps.gto.outputs.event == 'registration'
      run: |
        echo "[$GITHUB_REF] You got version '${{ steps.gto.outputs.version }}' registered for model '${{ steps.gto.outputs.name }}' "
        echo "[$GITHUB_REF] It is about time to publish it somewhere so others could use it!"
    - name: "Deploy (act on assigning a new stage)"
      if: steps.gto.outputs.event == 'assignment'
      run: |
        echo "[$GITHUB_REF] You got model '${{ steps.gto.outputs.name }}' of version '${{ steps.gto.outputs.version }}' promoted to stage '${{ steps.gto.outputs.stage }}'"
        echo "[$GITHUB_REF] It is about time to deploy it somewhere!"
