name: CML Report
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          if [ $GITHUB_REF = refs/heads/main ]; then
            PREVIOUS_REF=HEAD~1
          else
            PREVIOUS_REF=main
          fi

          cat <<EOF > report.md
          # CML Report
          ## Plots
          ![Precision & Recall](./prc.svg)
          ![Confusion Matrix](./confusion.svg)

          ## Metrics and Params
          ### ${PREVIOUS_REF} → workspace
          EOF

          dvc plots diff $PREVIOUS_REF workspace \
            --show-vega --targets evaluation/plots/precision_recall.json > vega.json
          vl2svg vega.json prc.svg

          dvc plots diff $PREVIOUS_REF workspace \
            --show-vega --targets evaluation/plots/confusion_matrix.json > vega.json
          vl2svg vega.json confusion.svg

          dvc exp diff $PREVIOUS_REF --show-md >> report.md

          cml comment create --publish --pr report.md
