name: CML Report
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          echo "# CML Report" > report.md

          echo "## Plots" >> report.md
          dvc plots diff main \
            --show-vega --targets prc.json > vega.json
          vl2svg vega.json prc.svg
          cml publish prc.svg --title "Precision & Recall" --md >> report.md

          echo "## Metrics" >> report.md
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]] ; then
            PREVIOUS_REF='HEAD~1'
          else
            PREVIOUS_REF='main'
          fi
          echo "### $PREVIOUS_REV → workspace" >> report.md
          dvc metrics diff $PREVIOUS_REV --show-md >> report.md

          cml send-comment report.md
