name: style-transfer

on: [push]

jobs:
  deploy-cloud-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: "Deploy GPU"
        env:
          repo_token: ${{ secrets.REPO_TOKEN }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=g3.4xlarge \
          --cloud-hdd-size 64 \
          --labels=cml-runner
  train:
    needs: deploy-cloud-runner
    runs-on: [self-hosted,cml-runner]
    container: 
      image: docker://dvcorg/cml-py3
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - name: "Train style transfer model"
        env:
          repo_token: ${{ secrets.REPO_TOKEN}}
        run: |
          apt-get update -y
          apt-get install python3-dev -y
          apt install imagemagick -y
          pip install -r requirements.txt
          
          # DVC stuff
          git fetch --prune
          dvc repro
          
          echo "# Style transfer" >> report.md
          git show origin/master:final_owl.png > master_owl.png
          convert +append final_owl.png master_owl.png out.png
          convert out.png -resize 75%  out_shrink.png
          echo "### Workspace vs. Main" >> report.md
          cml-publish out_shrink.png --md --title 'compare' >> report.md
          
          echo "## Training metrics" >> report.md
          dvc params diff master --show-md >> report.md
          
          echo >> report.md
          echo "## GPU info" >> report.md
          cat gpu_info.txt >> report.md
          
          cml-send-comment report.md 
