name: example-get-started test
on: 
  push:
    paths:
      - example-get-started/**
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'
permissions:
  contents: read
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    environment: aws
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: ${{ vars.AWS_SANDBOX_ROLE }}
        role-duration-seconds: 43200
    - name: Generate repo
      run: |
        pip install virtualenv
        cd example-get-started
        ./generate.sh
